apiVersion: v1
kind: Namespace
metadata:
  name: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-client
  namespace: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: goat-client
    spec:
      containers:
        - image: goatcommunity/client
          name: goat-client
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: goat-client-service
  namespace: v2
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: goat-client
