apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: goat-geoapi-external-secret
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: goat-geoapi-secret
    template:
      engineVersion: v2
      data: 
        postgres-url: postgresql://goat_v2:{{.postgres_password}}@dev.data.plan4better.de:5432/goat_v2
  data:
  - secretKey: postgres_password
    remoteRef:
      key: dev/DB/UserPassword
      property: goat_v2