apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-plan4better-de
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - 'argocd.plan4better.de'
    secretName: argocd-plan4better-de-tls
  rules:
  - host: 'argocd.plan4better.de'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                name: http