apiVersion: v1
kind: Namespace
metadata:
  name: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-docs
  namespace: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-docs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: goat-docs
    spec:
      containers:
        - image: ${DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          name: goat-docs
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goat-docs-service
  namespace: v2
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: goat-docs