apiVersion: v1
kind: Namespace
metadata:
  name: v2
---
apiVersion: v1
kind: Service
metadata:
  name: goat-geoapi-service
  namespace: v2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: goat-geoapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-geoapi
  namespace: v2
spec:
  minReadySeconds: 15
  replicas: 1
  selector:
    matchLabels:
      app: goat-geoapi
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: goat-geoapi
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: postgres-url
              name: goat-geoapi-secret
        image: busybox:1.35.0
        imagePullPolicy: IfNotPresent
        name: goat-geoapi
        ports:
        - containerPort: 5000
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: goat-geoapi-external-secret
  namespace: v2
spec:
  data:
  - remoteRef:
      key: dev/DB/UserPassword
      property: goat_v2
    secretKey: postgres_password
  refreshInterval: 60m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: goat-geoapi-secret
    template:
      data:
        postgres-url: postgresql://goat_v2:{{.postgres_password}}@dev.data.plan4better.de:5432/goat_v2
      engineVersion: v2
