########################################################################################
# "poetry install" composite action for client build                                   #
#--------------------------------------------------------------------------------------#
#                                                                                      #
# Usage in workflows steps:                                                            #
#                                                                                      #
#      - name: 📥 Poetry install                                                       #
#        uses: ./.github/actions/poetry-install                                        #
#        with:                                                                         #
#          cwd: ${{ github.workspace }}/apps/api # (default = '.')                     #
########################################################################################

name: "Poetry install"
description: "Run poetry install with cache enabled"
author: "Plan4Better GmbH"

inputs:
  cwd:
    description: "Changes process.cwd() if the project is not located on the root. Default to process.cwd()"
    required: false
    default: "."
  python_version:
    description: "Python version to use"
    required: false
    default: 3.11.4

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-0

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1.3.4
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Cache rotation keys
      id: cache-rotation
      shell: bash
      run: |
        echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('${{ inputs.cwd }}/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.cwd }}
      run: poetry install --no-interaction --no-root
      shell: bash
