name: "Api - Deploy"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: environment
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  deploy-api:
    name: deploy-api
    runs-on: ubuntu-latest
    needs: [checks]
    environment:
      name: ${{ needs.checks.outputs.env_name }}
    if: ${{ needs.checks.outputs.api-changed == 'true' }}
    timeout-minutes : 5
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🎡 Setup Kubectl
        uses: azure/setup-kubectl@v3

      - name: 🎡 Set Kubectl Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          
      - name: 🎡 Kustomize Bake
        id: bake
        uses: azure/k8s-bake@v2.4
        with:
            renderEngine: 'kustomize'
            kustomizationPath: ${{ github.workspace }}/infra/kustomize/api/overlays/${{ needs.checks.outputs.env_name }}
      
      - name: 🚀 Deploy to k8s
        uses: azure/k8s-deploy@v4
        with:
          namespace: ${{ needs.checks.outputs.env_name }}
          action: deploy
          strategy: basic
          manifests: |
            ${{ steps.bake.outputs.manifestsBundle }}
            ${{ github.workspace }}/infra/k8s/ingress/${{ needs.checks.outputs.env_name }}/ingress.yml
          images: |
            goatcommunity/api:${{ needs.checks.outputs.sha_short }}