name: "Client - Release"

on:
  workflow_call:
  workflow_dispatch:


defaults:
  run:
    working-directory: app/client

jobs:

  checks:
    name: checks
    uses: ./.github/workflows/checks.yml

  release-goat:
    name: release-goat
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
      
      - name: 🐳 Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🐳 Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: goatcommunity/client

      - name: 🐳 Build changed client
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/app/client
          file: ${{ github.workspace }}/app/client/apps/goat/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: |
             goatcommunity/client:${{ needs.checks.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      