name: "Client - Deploy"

on:
  workflow_call:

jobs:
  checks:
    name: environment
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  deploy-goat:
    name: deploy-goat
    runs-on: ubuntu-latest
    needs: [checks]
    environment:
      name: ${{ needs.checks.outputs.env_name }}
    if: ${{ needs.checks.outputs.client-goat-changed == 'true' }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🎡 Setup Kubectl
        uses: azure/setup-kubectl@v2.0

      - name: 🎡 Setup k8s context to home folder from base64 secret
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ~/.kube/config

      - name: 🚀 Deploy to k8s
        uses: azure/k8s-deploy@v4
        with:
          namespace: ${{ needs.checks.outputs.env_name }}
          action: deploy
          strategy: basic
          manifests: |
            infra/manifests/${{ needs.checks.outputs.env_name }}/client.yaml
          images: |
            goatcommunity/client:${{ github.sha }}