name: "GeoApi - Lint"

on:
  workflow_call:

defaults:
  run:
    working-directory: app/geoapi

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        
      - name: 📥 Checkout PR
        uses: ./.github/actions/pr-git-checkout

      - name: 📥 Poetry install
        uses: ./.github/actions/poetry-install
        with:
          cwd: ${{ github.workspace }}/app/geoapi

      - name: 🔬 Run linting
        run: poetry run bash scripts/lint.sh
