name: PR

on:
  pull_request:
    branches: [ prod, dev, staging, v2 ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true    

jobs:
  files-changed:
    name: detect-changes
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      pull-requests: read
      contents: read
    outputs:
        api: ${{ steps.changes.outputs.api }}
        client: ${{ steps.changes.outputs.client }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          api:
            - 'app/api/**'
          client:
            - 'app/client/**'
  build:
    runs-on: ubuntu-latest
    needs: files-changed
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8.4.0
      - uses: actions/checkout@v2
      - name: Build changed client
        if: ${{ needs.files-changed.outputs.client == 'true' }}
        run: make build-docker-image-pr -e COMPONENT=client
      - name: Build changed api
        if: ${{ needs.files-changed.outputs.api == 'true' }}
        run: make build-docker-image-pr -e COMPONENT=api
